### PR TITLE
Update a.txt

### PR DESCRIPTION
**Pull request by markolson**

### CODE REVIEW

**Comment by markolson** [comment]
@hoxworth is this project still active?

**Comment by llimllib** [comment]
I hope so! All my production projects are depending on it

**Comment by spacemunkay** [comment]
Please merge, need this fix ASAP and I don't feel like forking.

**Comment by jalewis** [comment]
CyberReadme

**Comment by hoxworth** [comment]
I've decided to pull this project from public consumption. I'm sorry all, I'm not really a jerk, but really, you didn't need my `alwaysPassTest` implementation anyway. Just `assert 1 == 1` and be done with it.

**Comment by hoxworth** [comment]
REJECTED.

**Comment by markolson** [comment]
Um rude tbh

**Comment by esauter5** [comment]
Hey guys,

So I just tried `npm install`ing this and it completed f*cked up my build. Here's the error:

``` javascript
ajdfoidsjfopidsfads
fds
fdsaf
dsf
adsf
dsfasfadsfdsfiodsjfojdopfjdasfidf
ds
fsad..21.erifjew
aef
efasdf
```

I'd really appreciate if you could fix this ASAP. This is an extremely critical project supporting 2 users.

TBH I haven't been this disappointed in open source maintainers since left-pad.

**Comment by esauter5** [comment]
Hey just checking in. Did you get a chance to read my comment yet? Is this fixed?

**Comment by hoxworth** [comment]
it is try again. alt-f4 if fail

**Pull request closed without merging**
